services:

  # App Service
  app:
    build:
      context: .
      target: php
      args:
        - APP_ENV:${APP_ENV}
    container_name: portalapp
    restart: unless-stopped
    environment:
      - APP_ENV:${APP_ENV}
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8181:8181
    networks:
      - auto-portal
    depends_on:
      - database

  # Database server
  database:
    image: mysql
    container_name: portaldb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - auto-portal

volumes:
  db-data:
networks:
  auto-portal:
    driver: bridge
